app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


class Quotes:
    '''
    Quote class to define quote Objects
    '''

    def __init__(self,id,author,quote,permalink):
        self.id =id
        self.author = author
        self.quote = quote
        self.permalink = permalink


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    blogs = db.relationship('Blog',backref = 'user',lazy = 'dynamic')
    comments = db.relationship('Comments',backref='user',lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'    


class Blog(db.Model):
     __tablename__ = 'blogs'

     id = db.Column(db.Integer,primary_key = True)
     blog  = db.Column(db.String(255))
     blog_content = db.Column(db.String(5000))
     blog_category =  db.Column(db.String(255))
     users_id = db.Column(db.Integer,db.ForeignKey("users.id"))
     likes = db.Column(db.Integer)
     dislikes = db.Column(db.Integer)
     comments = db.relationship('Comments',backref =  'blog_id',lazy = "dynamic")

     def save_blog(self):
         db.session.add(self)
         db.session.commit()

     @classmethod
     def get_blog(cls,id):
        blog = Blog.query.filter_by(id=id).first()
        return blog
     
     @classmethod
     def get_blogs(cls,blog_category):
        blogs = Blog.query.filter_by(blog_category = blog_category).all()
        return blogs


class Comments(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String())
    blog = db.Column(db.Integer,db.ForeignKey("blogs.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,blog):
        comments = Comments.query.filter_by(blog_id = blog).all()
        return comments  

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class BlogForm(FlaskForm):

    title = StringField('Type your title',validators=[Required()])
    author = StringField('Type your name',validators=[Required()])
    category = SelectField('Type',choices=[('blogs','Blogs blog')],validators=[Required()])
    blog= TextAreaField('write your content', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')


class CommentsForm(FlaskForm):
    text = TextAreaField('Leave a comment:',validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #importing bluepring
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required,current_user
from ..models import User,Blog,Comments,Quotes
from .forms import BlogForm, UpdateProfile,CommentsForm
from .. import db,photos
from ..requests import get_quote



@main.route('/')
def index():

    '''
    function to display blog categories
    '''
    #Getting pitches from different categories
    blogs_blogs = Blog.get_blogs('blogs')
    quote = get_quote()
    

    
   
    return render_template('index.html',blogs = blogs_blogs,quote = quote)



@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)
    

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/blog/new/', methods = ['GET','POST'])
@login_required
def add_blog():
    form = BlogForm()
    if form.validate_on_submit():
        blog = form.blog.data
        category = form.category.data
        new_blog = Blog(blog_content = blog,blog_category = category,user = current_user, likes=0, dislikes=0)
        new_blog.save_blog()
        return redirect(url_for('.index'))

    title = 'Create Blog'
    return render_template('create_blog.html',title = title, blog_form = form)

@main.route('/blog/<int:id>', methods = ['GET','POST'])
def blog(id):
    blog = Blog.get_blog(id)
    

    if request.args.get("likes"):
        blog.likes += 1

        db.session.add(blog)
        db.session.commit()

        return redirect("/blog/{blog_id}".format(blog_id=blog.id)) 

    elif request.args.get("dislikes"):
        blog.dislikes += 1

        db.session.add(blog)
        db.session.commit()

        return redirect("/blog/{blog_id}".format(blog_id=blog.id))

    comment_form = CommentsForm()
    if comment_form.validate_on_submit():
        comment = comment_form.text.data

        new_comment = Comments(comment = comment,user = current_user,blog_id = blog)
        

        new_comment.save_comment()
    comments = Comments.get_comments(blog)

    return render_template("blog.html", blog = blog, comment_form = comment_form, comments = comments)





@main.route('/blog/update/<int:id>', methods = ['GET','POST'])
@login_required
def update_blog(id):
    blog = Blog.query.get_or_404(id)
    if blog.user != current_user:
        abort(403)
        form = BlogForm()
        if form.validate_on_submit():
            blog.title = form.title.data
            blog.content = form.content.data

            db.session.commit()
            flash ('your post has been updated','success')

            return redirect(url_for('blog',blog_id = blog.id))
            
        elif request.method =='GET':
                form.title.data = blog.title
                form.content.data = blog.content 

        return render_template('create_blog.html',title = 'Update Blog', blog_form = form)

@main.route('/blog/delete/<int:id>', methods = ['GET', 'POST'])
@login_required
def delete_blog(id):
    blog = Blog.query.get_or_404(id)
    if blog.user != current_user:
        abort(403)
        db.session.delete(blog)
        db.session.commit()

        flash('Your blog has been deleted' 'success')

        
    return redirect(url_for('main.index'))

app/templates/base.html
{% extends 'bootstrap/base.html' %}
<!-- Navbar block -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html>
        
        
        
        {% block content %}
        <div class="container">
            <div class="row">
               
                <p>{{blog.blog_content}}</p>
                <span>
                <p>Posted by {{blog.user.username| capitalize}}</p>
                <a href="/blog/{{blog.id}}?likes=1">
                <i class="material-icons"></i>
                    <i class="material-icons">Likes</i>
                </a>{{blog.likes}} <a href="/blog/{{blog.id}}?dislikes=1">
                    <i class="material-icons">Dislikes</i>
                </a>{{blog.dislikes}}</span>
                
                <br>
                <br>
                <a class="btn btn-primary" href="/blog/new/"> Create Blog</a>
                <br>
                <br>
               
                <a class="btn btn-success" href="url_for('main.update_blog',id = blog.id)}}"> Update Blog</a>
                <br>
                <br>
                <a class="btn btn-danger" href="{{url_for('main.delete_blog',id = blog.id)}}"> Delete Blog</a>
              
               
                 
            </div>
            <div class="row">
                <hr>
                
                    {{ wtf.quick_form(comment_form) }}
                
                <h3>Comments</h3>
                {{macro.displayComments(comments)}}
            </div>
        </div>
        {% endblock %}

app/templates/create_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8">
            <h1> CREATE BLOG</h1>
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(blog_form) }}
             
        </div>
        
        
    </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}




    
    {% block content %}
    <!-- Card -->
<div class="card">
    <!-- Card content -->
    <div class="card-body">
  
      <!-- Title -->
      <p>{{quote.quote}}</p>
      <h2 class="card-title" style="color:white;"> BLOGS</h2>
      
      <!-- Text -->
      <p class="card-text"> {{ macro.displayBlogsList(blogs)}}</p>
     
    </div>
  
  </div>
  
<style>

.card{
    background-color:olive;
    
}
.card-body{
  flex-direction: row;
  margin-left: 25%;
}
</style>
  {% endblock%} 

   
       

app/templates/macros.html
{% macro displayBlogsList(blog_list) %}

    {% for blog in blog_list %}
        <div class="col-md-6">
            <p>{{ blog_content }}</p>
            
            <p class="text-center">{{blog.blog_content}}</p>
            
            <h5 class="text-center">Published by: {{blog.user.username}}</h5>
            <li class="text-center">
                    <a class="btn btn-info" href="/blog/{{blog.id}}">Read Blog</a>
                </li>
        </div>

    {% endfor %}

{% endmacro %}

{% macro displayComments(comments_list) %}
    {% for comment in comments_list %}
        <div class="col-md-12">
            <h5>{{comment.user.username}}</h5>
            <p>{{comment.comment}}</p>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><h3 style="color:white;"> HOME </h3></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"><h3 style="color:white;">BLOGS</h3></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                    <li style="color:white;padding:15px;">{{current_user.username}}</li>
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}"><h5 style="color:white;">Sign in as a Writer</h5></a></li>
                    {%endif%}
                  </ul>

        </div>

<ul class="nav navbar-nav navbar-right">
                 
                  <li><a href="{{url_for('auth.subscribe')}}"><h5 style="color:white;" >Subscribe</h5></a></li>
                  
                </ul>
    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
      {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}" class = "btn btn-secondary"><h2>Edit profile</h2></a>
  {% endif %}

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

   
  </div>
  <br>
  <br>
        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <br>
      <br>
      <input type="submit" class = "btn btn-primary">
    </form>
      {% endif %}
  </div>
  <br>
  <br>
  <div>
      <a class="ratings" href="/blog/new/"> Create a Blog</a>
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/quotes.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
 
    {% block content %}
    <div class="container">
    <h1> GENERAL QUOTES BLOG </h1>

    <div class="well-lg" id="random">
            <h1>Random Quote</h1> <br>
            <p>quote ID: {{quote.id}}</p> 
            <p>{{quote.quote}}</p>
            <p>Author: {{quote.author}}</p> 
            <p>{{quote.permalink}}</p> 
        </div>
    </div>
    <div class="container">

        <h1>QUOTES BLOG</h1>

        <div class="row">
            {% for blogs in blogs %}
            <div class="col-md-3">
                <div class="container">
                    <h1>{{blogs.title}}</h1>
                    <p>{{ new_blogs.content }}</p>
                    <a href="{{url_for('main.new_blog',blog_id = blogs.id)}}" class="btn btn-info"> Add a comment</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
    {% endblock %}
</body>
</html>